modLoader="javafml"
loaderVersion="[35,)"
license="Apache License"
issueTrackerURL="http://www.github.com/MelanX/yellowsnow/issues/"

[[mods]]
modId="yellowsnow"
version="${file.jarVersion}"
displayName="Yellow Snow"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/yellowsnow.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="yellowsnow.png"
credits=""
authors="MelanX"
description='''

'''

[[dependencies.yellowsnow]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.yellowsnow]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4, 1.17)"
    ordering="NONE"
    side="BOTH"
